modLoader = "javafml"
loaderVersion = "[50,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"
logoFile = "elfeatures_banner.png"
clientSideOnly = true

[[mods]]
modId = "elfeatures"
version = "${mod_version}"
displayName = "${mod_name}"
displayTest = "IGNORE_ALL_VERSION"
description = '''
${mod_full_description}
'''
displayURL = "${mod_website}"
authors = "${mod_authors}"

[[dependencies.elfeatures]]
modId = "forge"
mandatory = true
versionRange = "[50,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.elfeatures]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "CLIENT"