module_name = vanilla-v3
used_modules = core,shared:mixin,platform:vanilla:loader,platform:vanilla:agent,platform:vanilla:tweaker
java_version = 25
runtime_names = official

# platform specific
minecraft_version = 26.1
