module_name = vanilla-v2
used_modules = core,shared:mixin,platform:vanilla:loader,platform:vanilla:agent,platform:vanilla:tweaker
base_jar_task = remapJar
runtime_names = intermediary

# platform specific
minecraft_version = 1.14.4
yarn_mappings = 1.14.4+build.18
